# Generated by Django 5.1.2 on 2025-01-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_shelter_remove_event_created_by_remove_event_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petreport',
            name='customer_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
